name: test CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test-job:
    runs-on: demo-runner
    steps:
      - run: echo "hello" > file.txt
      - uses: actions/upload-artifact@v4.2.0
        with:
          name: my-artifact
          path: ./
